package com.iqiyi.db.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "tb_recently".
 */
@Entity(nameInDb = "tb_recently")
public class RecentlyInfo {

    @Id
    private Long id;
    private String oid;
    private String vid;
    private String title;
    private String content;
    private String createTime;

    @Generated
    public RecentlyInfo() {
    }

    public RecentlyInfo(Long id) {
        this.id = id;
    }

    @Generated
    public RecentlyInfo(Long id, String oid, String vid, String title, String content, String createTime) {
        this.id = id;
        this.oid = oid;
        this.vid = vid;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOid() {
        return oid;
    }

    public void setOid(String oid) {
        this.oid = oid;
    }

    public String getVid() {
        return vid;
    }

    public void setVid(String vid) {
        this.vid = vid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
