package com.iqiyi.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.iqiyi.db.entity.RecentlyInfo;
import com.iqiyi.db.entity.StarInfo;

import com.iqiyi.db.dao.RecentlyInfoDao;
import com.iqiyi.db.dao.StarInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentlyInfoDaoConfig;
    private final DaoConfig starInfoDaoConfig;

    private final RecentlyInfoDao recentlyInfoDao;
    private final StarInfoDao starInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentlyInfoDaoConfig = daoConfigMap.get(RecentlyInfoDao.class).clone();
        recentlyInfoDaoConfig.initIdentityScope(type);

        starInfoDaoConfig = daoConfigMap.get(StarInfoDao.class).clone();
        starInfoDaoConfig.initIdentityScope(type);

        recentlyInfoDao = new RecentlyInfoDao(recentlyInfoDaoConfig, this);
        starInfoDao = new StarInfoDao(starInfoDaoConfig, this);

        registerDao(RecentlyInfo.class, recentlyInfoDao);
        registerDao(StarInfo.class, starInfoDao);
    }
    
    public void clear() {
        recentlyInfoDaoConfig.clearIdentityScope();
        starInfoDaoConfig.clearIdentityScope();
    }

    public RecentlyInfoDao getRecentlyInfoDao() {
        return recentlyInfoDao;
    }

    public StarInfoDao getStarInfoDao() {
        return starInfoDao;
    }

}
